# Services Package

# ESPN Client
from backend.services.espn_client import (
    ESPNClient,
    create_espn_client,
    ESPNClientError,
    ESPNAuthenticationError,
    ESPNLeagueNotFoundError,
    ESPNRateLimitError,
    ESPNConnectionError,
)

# Cache Service
from backend.services.cache_service import (
    CacheService,
    CacheEntry,
    CacheTTL,
    get_cache,
    reset_cache,
)

# League Service
from backend.services.league_service import (
    create_league,
    get_league_by_id,
    get_league_or_404,
    get_user_leagues,
    get_league_by_espn_id,
    get_leagues_needing_refresh,
    update_league,
    update_league_settings,
    update_league_cookies,
    mark_league_updated,
    delete_league,
    get_league_with_teams,
    get_league_credentials,
    LeagueServiceError,
    LeagueNotFoundError,
    LeagueAlreadyExistsError,
    LeagueAccessDeniedError,
)

# Team Service
from backend.services.team_service import (
    create_team,
    create_or_update_team,
    bulk_create_teams,
    get_team_by_id,
    get_team_or_404,
    get_team_by_espn_id,
    get_league_teams,
    get_league_standings,
    update_team,
    update_team_projections,
    update_team_standings,
    delete_team,
    delete_league_teams,
    add_player_to_roster,
    remove_player_from_roster,
    get_team_roster,
    update_team_roster,
    TeamServiceError,
    TeamNotFoundError,
    TeamAlreadyExistsError,
    RosterError,
)

# Player Service
from backend.services.player_service import (
    create_player,
    create_or_update_player,
    bulk_create_players,
    get_player_by_id,
    get_player_or_404,
    get_player_by_espn_id,
    search_players,
    get_players_by_team,
    get_players_by_position,
    get_injured_players,
    update_player,
    update_player_injury,
    delete_player,
    add_player_stats,
    get_player_stats,
    get_player_season_stats,
    get_player_game_stats,
    bulk_add_stats,
    add_projection,
    get_player_projections,
    get_league_projections,
    PlayerServiceError,
    PlayerNotFoundError,
    PlayerAlreadyExistsError,
    StatsError,
)

__all__ = [
    # ESPN Client
    'ESPNClient',
    'create_espn_client',
    'ESPNClientError',
    'ESPNAuthenticationError',
    'ESPNLeagueNotFoundError',
    'ESPNRateLimitError',
    'ESPNConnectionError',
    # Cache Service
    'CacheService',
    'CacheEntry',
    'CacheTTL',
    'get_cache',
    'reset_cache',
    # League Service
    'create_league',
    'get_league_by_id',
    'get_league_or_404',
    'get_user_leagues',
    'get_league_by_espn_id',
    'get_leagues_needing_refresh',
    'update_league',
    'update_league_settings',
    'update_league_cookies',
    'mark_league_updated',
    'delete_league',
    'get_league_with_teams',
    'get_league_credentials',
    'LeagueServiceError',
    'LeagueNotFoundError',
    'LeagueAlreadyExistsError',
    'LeagueAccessDeniedError',
    # Team Service
    'create_team',
    'create_or_update_team',
    'bulk_create_teams',
    'get_team_by_id',
    'get_team_or_404',
    'get_team_by_espn_id',
    'get_league_teams',
    'get_league_standings',
    'update_team',
    'update_team_projections',
    'update_team_standings',
    'delete_team',
    'delete_league_teams',
    'add_player_to_roster',
    'remove_player_from_roster',
    'get_team_roster',
    'update_team_roster',
    'TeamServiceError',
    'TeamNotFoundError',
    'TeamAlreadyExistsError',
    'RosterError',
    # Player Service
    'create_player',
    'create_or_update_player',
    'bulk_create_players',
    'get_player_by_id',
    'get_player_or_404',
    'get_player_by_espn_id',
    'search_players',
    'get_players_by_team',
    'get_players_by_position',
    'get_injured_players',
    'update_player',
    'update_player_injury',
    'delete_player',
    'add_player_stats',
    'get_player_stats',
    'get_player_season_stats',
    'get_player_game_stats',
    'bulk_add_stats',
    'add_projection',
    'get_player_projections',
    'get_league_projections',
    'PlayerServiceError',
    'PlayerNotFoundError',
    'PlayerAlreadyExistsError',
    'StatsError',
    # Scheduler Service
    'SchedulerService',
    'SchedulerConfig',
    'get_scheduler',
    'init_scheduler',
    'shutdown_scheduler',
    'refresh_all_leagues',
    'refresh_single_league',
]

# Scheduler Service
from backend.services.scheduler_service import (
    SchedulerService,
    SchedulerConfig,
    get_scheduler,
    init_scheduler,
    shutdown_scheduler,
    refresh_all_leagues,
    refresh_single_league,
)
