"""Add PlayerBirthDate cache table

Revision ID: 406aee254abb
Revises: 440a1dadf32f
Create Date: 2026-04-21 21:16:37.511402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '406aee254abb'
down_revision = '440a1dadf32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nba_player_stats')

    # Create PlayerBirthDate cache table
    op.create_table('player_birth_dates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('espn_player_id', sa.Integer(), nullable=False),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('cached_season', sa.Integer(), nullable=False),
        sa.Column('cached_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('espn_player_id', 'cached_season', name='unique_player_season_birthdate')
    )
    op.create_index(op.f('ix_player_birth_dates_espn_player_id'), 'player_birth_dates', ['espn_player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop PlayerBirthDate table
    op.drop_index(op.f('ix_player_birth_dates_espn_player_id'), table_name='player_birth_dates')
    op.drop_table('player_birth_dates')

    op.create_table('nba_player_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.Column('league_wide_averages', sqlite.JSON(), nullable=False),
    sa.Column('total_players', sa.INTEGER(), nullable=False),
    sa.Column('min_games_played', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
