"""Add active_roster_limit to leagues

Revision ID: 440a1dadf32f
Revises: 78f3a231b207
Create Date: 2026-03-02 19:39:12.065986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440a1dadf32f'
down_revision = '78f3a231b207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_roster_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('active_roster_limit')

    # ### end Alembic commands ###
