"""Add trade suggestion mode to leagues

Revision ID: 78f3a231b207
Revises: 7df293af1e22
Create Date: 2026-02-22 17:13:25.879395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f3a231b207'
down_revision = '7df293af1e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade_suggestion_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('trade_suggestion_mode')

    # ### end Alembic commands ###
