"""Initial migration with projection settings

Revision ID: 7df293af1e22
Revises: 
Create Date: 2026-02-18 17:04:37.475409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df293af1e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projection_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('flat_game_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('flat_game_rate')
        batch_op.drop_column('projection_method')

    # ### end Alembic commands ###
